CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, wallet_address VARCHAR(66) NOT NULL UNIQUE, email VARCHAR(255) UNIQUE, created_at TIMESTAMPTZ DEFAULT NOW(), last_login TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS wallets (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, chain_id VARCHAR(20) NOT NULL, wallet_address VARCHAR(255) NOT NULL, wallet_type VARCHAR(50) DEFAULT 'active', is_watch_only BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE (user_id, chain_id, wallet_address));
CREATE TABLE IF NOT EXISTS transactions (id BIGSERIAL PRIMARY KEY, chain_id VARCHAR(20) NOT NULL, tx_hash VARCHAR(66) NOT NULL UNIQUE, from_address VARCHAR(66), to_address VARCHAR(66), value NUMERIC(78, 18) NOT NULL DEFAULT 0, gas_price NUMERIC(78, 18), gas_limit INTEGER, gas_used INTEGER, status VARCHAR(50) DEFAULT 'pending', transaction_type VARCHAR(50) NOT NULL, nonce INTEGER, confirmations INTEGER DEFAULT 0, raw_payload JSONB DEFAULT '{}'::jsonb, decoded_logs JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), confirmed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS blocks (id BIGSERIAL PRIMARY KEY, chain_id VARCHAR(20) NOT NULL, block_height BIGINT NOT NULL UNIQUE, block_hash VARCHAR(66) NOT NULL, parent_hash VARCHAR(66), timestamp TIMESTAMPTZ NOT NULL, tx_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS nfts (id BIGSERIAL PRIMARY KEY, contract_address VARCHAR(66) NOT NULL, token_id VARCHAR(255) NOT NULL, name VARCHAR(255), symbol VARCHAR(50), standard VARCHAR(20) NOT NULL, owner_address VARCHAR(66) NOT NULL, metadata_uri TEXT, last_synced_block BIGINT, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE (contract_address, token_id));
CREATE TABLE IF NOT EXISTS token_holdings (id BIGSERIAL PRIMARY KEY, wallet_id BIGINT REFERENCES wallets(id) ON DELETE CASCADE, contract_address VARCHAR(66) NOT NULL, symbol VARCHAR(20) NOT NULL, name VARCHAR(255), decimals INTEGER DEFAULT 18, balance NUMERIC(78, 18) NOT NULL DEFAULT 0, total_supply NUMERIC(78, 18), last_updated TIMESTAMPTZ DEFAULT NOW(), UNIQUE (wallet_id, contract_address));
CREATE TABLE IF NOT EXISTS defi_positions (id BIGSERIAL PRIMARY KEY, wallet_id BIGINT REFERENCES wallets(id) ON DELETE CASCADE, protocol_name VARCHAR(255) NOT NULL, contract_address VARCHAR(66), position_type VARCHAR(50) NOT NULL, amount NUMERIC(78, 18) NOT NULL, reward_token VARCHAR(66), apr NUMERIC(10, 4), status VARCHAR(50) DEFAULT 'active', unlocked_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_transactions_chain_status ON transactions(chain_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_from_to ON transactions(from_address, to_address);
CREATE INDEX IF NOT EXISTS idx_wallets_user_chain ON wallets(user_id, chain_id);
CREATE INDEX IF NOT EXISTS idx_nfts_owner ON nfts(owner_address);
CREATE INDEX IF NOT EXISTS idx_token_holdings_wallet ON token_holdings(wallet_id);
CREATE INDEX IF NOT EXISTS idx_defi_positions_wallet ON defi_positions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_blocks_chain_height ON blocks(chain_id, block_height DESC);
COMMENT ON TABLE users IS 'Core user registry linked to blockchain identities';
COMMENT ON TABLE wallets IS 'Multi-chain wallet tracking per user';
COMMENT ON TABLE transactions IS 'Immutable transaction history from all integrated chains';
COMMENT ON TABLE nfts IS 'NFT inventory across ERC-721, ERC-1155, and Solana standards';
COMMENT ON TABLE token_holdings IS 'ERC-20 token balances per wallet';
COMMENT ON TABLE defi_positions IS 'DeFi staking/liquidity/yield farming positions';