CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, wallet_address VARCHAR(66) UNIQUE NOT NULL, email VARCHAR(255), created_at TIMESTAMP DEFAULT NOW(), last_login TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS wallets (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, chain_id INTEGER NOT NULL, address VARCHAR(66) NOT NULL, label VARCHAR(100), is_primary BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS transactions (id BIGSERIAL PRIMARY KEY, hash VARCHAR(66) UNIQUE NOT NULL, from_address VARCHAR(66), to_address VARCHAR(66), value NUMERIC(78, 0) NOT NULL, gas_price NUMERIC(78, 0), gas_limit INTEGER NOT NULL, status VARCHAR(50) DEFAULT 'pending', block_number BIGINT, timestamp TIMESTAMP DEFAULT NOW(), type VARCHAR(20) CHECK (type IN ('transfer','swap','mint','burn')));
CREATE TABLE IF NOT EXISTS blocks (number BIGINT PRIMARY KEY, hash VARCHAR(66) UNIQUE NOT NULL, parent_hash VARCHAR(66), miner VARCHAR(66), timestamp TIMESTAMP NOT NULL, difficulty BIGINT, total_difficulty BIGINT, size INTEGER, tx_count INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS tokens (id BIGSERIAL PRIMARY KEY, symbol VARCHAR(20) NOT NULL, name VARCHAR(100) NOT NULL, decimals INTEGER DEFAULT 18, contract_address VARCHAR(66) UNIQUE NOT NULL, standard VARCHAR(20) CHECK (standard IN ('ERC-20','ERC-721','ERC-1155')));
CREATE TABLE IF NOT EXISTS nfts (id BIGSERIAL PRIMARY KEY, token_id VARCHAR(66) NOT NULL, contract_address VARCHAR(66) NOT NULL, owner_address VARCHAR(66) NOT NULL, token_uri TEXT, metadata JSONB, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS defi_positions (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, token_id BIGINT REFERENCES tokens(id), amount NUMERIC(78, 0) NOT NULL, apy NUMERIC(10, 2), status VARCHAR(50) DEFAULT 'active', created_at TIMESTAMP DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_transactions_from ON transactions(from_address);
CREATE INDEX IF NOT EXISTS idx_transactions_to ON transactions(to_address);
CREATE INDEX IF NOT EXISTS idx_transactions_block ON transactions(block_number);
CREATE INDEX IF NOT EXISTS idx_wallets_user ON wallets(user_id);
CREATE INDEX IF NOT EXISTS idx_nfts_owner ON nfts(owner_address);
